version: "3"

services:
    app:
      container_name: app
      build: ./api/docker
      volumes:
        - ./api:/var/www
      ports:
        - "9000:9000"
      command: php artisan swoole:http start
      depends_on: 
        - mysql

    mysql:
        container_name: "mysql"
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./api/docker/dbdata:/var/lib/mysql"        
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: test 
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    # SPA com Vuex
    front:
      container_name: "front"
      build: ./front
      volumes:
        - ./front:/app:rw
        - /front/node_modules
      ports:
        - "80:3000"
      depends_on: 
        - mysql        
        - app