# v2 syntax
version: '2'

# Named volumes
volumes:
  test-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2-nginx
    container_name: test-app
    volumes:
      - ./api:/var/www/app
    ports:
      - "9000:8080"
    links:
      - mysql
      
  # SPA com Vuex
  front:
    container_name: "front"
    build: ./front
    volumes:
      - ./front:/app:rw
      - /front/node_modules
    ports:
      - "80:3000"
    # depends_on:
    #   - app
